name: build

on:
  push:
    branches: [ "minified" ]
  pull_request:
    branches: [ "minified" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@v4

      - name: auto minify the files
        uses: nizarmah/auto-minify@v3
        with: 
            overwrite: true
      - name: auto commit the minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "bot: Add auto minified files"

      - name: Use Node.js (dependency)
        uses: actions/setup-node@v3
        with:
            node-version: 16

      - name: static file projects
        run: node ./_data/updateProjects.js

      - name: Check for modified files
        id: git-check
        run: echo modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi) >> $GITHUB_OUTPUT

      - name: Push
        if: steps.git-check.outputs.modified == 'true'
        run: |
            git config --global user.email "robertohelper@outlook.com"
            git config --global user.name "Gwilom-Bot"
            git add .
            git commit -am "feature: Update static project files" || true
            git push || git pull --rebase && git push