name: build

on:
  push:
    branches: [ "minified" ]

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-static-site:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@v4

      - name: auto minify the files
        uses: nizarmah/auto-minify@v3
        with: 
            overwrite: true
      - name: auto commit the minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "refactor: updated js/css to minified files"

      - name: Use Node.js (dependency)
        uses: actions/setup-node@v3
        with:
            node-version: 16

      - name: static file projects
        run: node ./src/site_builder/updateProjects.js

      - name: Check for modified files
        id: git-check
        run: echo modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi) >> $GITHUB_OUTPUT

      - name: Push
        if: steps.git-check.outputs.modified == 'true'
        run: |
            git config --global user.email "robertohelper@outlook.com"
            git config --global user.name "Gwilom-Bot"
            git add .
            git commit -am "refactor: Update static project files" || true
            git push || git pull --rebase && git push

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: '.'

  deploy:
    needs: build-static-site
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: static-site
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './src/static_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4