name: build

on:
  push:
    branches: [ "testing" ]

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-static-site:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@v4

      - name: Use Node.js (dependency)
        uses: actions/setup-node@v3
        with:
            node-version: 16

      - name: Build page index file
        run: node ./src/site_builder/updateProjects.js

        # html minifier but it's also a CSS and JS for some reason
      - run: npm install -g html-minifier

      - name: Minify HTML files
        run: for i in ./src/static_site/*.html; do html-minifier -exec html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true $i -o $i; done

      - name: Check for modified files
        id: git-check
        run: echo modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi) >> $GITHUB_OUTPUT

      - name: Push to branch
        if: steps.git-check.outputs.modified == 'true'
        run: |
            git config --global user.email "robertohelper@outlook.com"
            git config --global user.name "Gwilom-Bot"
            git add .
            git commit -am "refactor: Updated static project files (generated index and minified files)" || true
            git push || git pull --rebase && git push

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: '.'

