name: build

on:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-static-site:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repository
        uses: actions/checkout@v4

      - name: Use Node.js (dependency)
        uses: actions/setup-node@v3
        with:
            node-version: 16

      - name: Build page index file
        run: node ./src/site_builder/updateProjects.js

        # js and css minifier
      - name: auto minify the files
        uses: nizarmah/auto-minify@v3
        with: 
            overwrite: true
      - name: auto commit the minified files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
            commit_message: "refactor: JS and CSS have been minified files"

        # html minifier
      - run: npm install -g html-minifier

      - name: Minify HTML files
        run: find ./static_site -type f -name "*.html" -exec html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true \;

      - name: Check for modified files
        id: git-check
        run: echo modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi) >> $GITHUB_OUTPUT

      - name: Push to branch
        if: steps.git-check.outputs.modified == 'true'
        run: |
            git config --global user.email "robertohelper@outlook.com"
            git config --global user.name "Gwilom-Bot"
            git add .
            git commit -am "refactor: Update static project files" || true
            git push || git pull --rebase && git push

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: '.'